content = open('D:/RGSmart/contenido/pages/gracias.html', 'rb').read()
text = content.decode('utf-8', errors='replace')
text = text.replace('\ufffd', '')
text = text.replace('Â¡', '¡')
text = text.replace('â€"', '—')
text = text.replace('â€™', "'")
text = text.replace('âœ…', '✅')
text = text.replace('â†', '←')
text = text.replace('Ã©', 'é')
text = text.replace('Ã³', 'ó')
text = text.replace('Ã­', 'í')
text = text.replace('Ã¡', 'á')
text = text.replace('Ãº', 'ú')
text = text.replace('Ã±', 'ñ')
open('D:/RGSmart/contenido/pages/gracias.html', 'w', encoding='utf-8').write(text)
print('Listo')